name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aantunes/clang-wasm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Tests
        run: |
          make clean test
          make codecov TOKEN=${{ secrets.CODECOV_TOKEN }} ID=${{ github.run_id }}